import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { NextUIProvider } from "@nextui-org/react";
import { Appbar } from "../components/Appbar";
import { Footer } from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "FlowStack",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
  }: {
    children: React.ReactNode;
  }): JSX.Element {
    return (
      <html lang="en">
          <body className={inter.className}>
        <NextUIProvider>
              <Appbar />
              {children}
              <Footer />
        </NextUIProvider>
          </body>
      </html>
    );
  }
